{% set name = "igwn-lldd-fdio" %}
{% set version = "0.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://git.ligo.org/computing/lowlatency/{{ name }}/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4ef3ad4a26d501fe6236c86882a998694703c3e3119c017ce9caf6cb2d342822

build:
  entry_points:
    - kafka2fdio = igwn_lldd_fdio.kafka2fdio:main
    - fdio2kafka = igwn_lldd_fdio.fdio2kafka:main
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=38.2.5
  run:
    - configargparse
    - igwn-lldd-common
    - pyfd
    - python >=3.6
    - pythonvirgotools

test:
  requires:
    - pip
    - pytest
    - flaky
  commands:
    # check metadata
    - python -m pip check igwn-lldd-fdio
    - python -m pip show igwn-lldd-fdio
    # run test suite
    - python -m pytest -ra -v --pyargs igwn_lldd_fdio.tests
    # check entry points
    - fdio2kafka --help
    - kafka2fdio --help

about:
  home: https://git.ligo.org/computing/lowlatency/igwn-lldd-fdio
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: The IGWN - Low Latency Data Distribution (lldd) - Frame distribtion Input/ Output (FdIO) is software to distribute low latency data used by the International Gravitational-Wave Observatory Network (IGWN) using a FdIOServer.
extra:
  recipe-maintainers:
    - rhyspoulton
